### ISSUE TITLE
Webhook for Bitbucket server causes error with unsupported Content-Type

### ISSUE THREAD

**Issue by haraldatbmw** [fluxcd/notification-controller#103]
I'm trying to trigger the notification-controller with a Bitbucket POST webhook.
My Bitbucket server sends a HTTP request with the header `Content-type: application/json; charset=utf-8`.
The flux notification-controller fails with this error:

```json
{
	"level":"error",
	"ts":"2020-12-14T14:41:21.652Z",
	"logger":"receiver-server",
	"msg":"unable to validate payload",
	"receiver":"bitbucket-receiver",
	"error":"the Bitbucket server signature header is invalid, err: Webhook request has unsupported Content-Type \"application/json; charset=UTF-8\""
}
```

```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: bitbucket-receiver
  namespace: flux-system
spec:
  type: bitbucket
  events:
  - "repo:refs_changed"
  secretRef:
    name: webhook-token
  resources:
  - kind: GitRepository
    name: flux-system
```
