### ISSUE TITLE
GitHub Alert fails with "missing revision metadata" on GitRepository eventsource

### ISSUE THREAD

**Issue by tobbbles** [fluxcd/notification-controller#106]
I have configured a minimal notification Provider and Alert for GitHub, however the event is being dropped from the notification-controller with the following error `missing revision metadata`, the full details are below.

I would expect the event to be fired and handled correctly. Is there any more I can do to help debug here?

#### Flux Component versions
```
image: ghcr.io/fluxcd/helm-controller:v0.4.4
image: ghcr.io/fluxcd/kustomize-controller:v0.5.3
image: ghcr.io/fluxcd/notification-controller:v0.5.0
image: ghcr.io/fluxcd/source-controller:v0.5.6
```

#### Error Log:
```json
{"level":"info","ts":"2021-01-06T15:13:59.632Z","logger":"event-server","msg":"Dispatching event","object":"flux-system/flux-system","kind":"GitRepository","message":"Fetched revision: main/029fc93e2718bed1b58c171e077467b269076f62"}
{"level":"error","ts":"2021-01-06T15:13:59.634Z","logger":"event-server","msg":"failed to send notification","object":"flux-system/flux-system","kind":"GitRepository","error":"missing revision metadata"}
```

#### Manifests:
```yaml
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: github-alert
  namespace: flux-system
spec:
  eventSeverity: info
  eventSources:
  - kind: GitRepository
    name: flux-system
    namespace: flux-system
  providerRef:
    name: github
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: github
  namespace: flux-system
spec:
  address: https://github.com/tobbbles/flux
  secretRef:
    name: github-api-token
  type: github
```
