### ISSUE TITLE
Request to Support message_thread_id Parameter for Telegram Provider

### ISSUE THREAD

**Issue by v1km4n** [fluxcd/notification-controller#1063]
**Summary**
The current Telegram provider in the notification-controller does not support sending alerts to Telegram forums (chats with topics).

This feature can be implemented by extending the Telegram provider to accept the message_thread_id parameter in its notification configuration.

**Suggested Implementation**
The Telegram Bot API supports the message_thread_id parameter for the sendMessage method (as detailed in the [Telegram Bot API documentation](https://core.telegram.org/bots/api#sendmessage)).

**Current behavior**: The Telegram provider sends messages to the default chat without the option to specify a topic. As a result there is currently no way to utilize Telegram chats that use topics feature.

**Desired behavior**: Add support for the message_thread_id parameter to the configuration of the Telegram provider so that notifications can be sent to specific threads in a Telegram forum. Provider manifest will the look like so:

```
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: telegram-alerts
spec:
  type: telegram
  channel: "*chat_id*"
  message_thread_id: "*message_thread_id*"
  secretRef:
    name: telegram-bot-token
```

**Comment by v1km4n** [comment]
Ok after reading through the shoutrrr lib I [found out that it supports Telegram topics](https://github.com/containrrr/shoutrrr/pull/362/files) which means that no changes are needed in the FluxCD Notification Controller in order to send Telegram alerts to said topics.

For anyone who would come across the same situation here's a provider manifest that should work:
```
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: telegram-alerts
spec:
  type: telegram
  channel: "*chat_id*:*message_thread_id*"
  secretRef:
    name: telegram-bot-token
```
