### ISSUE TITLE
Failed creating Gitea client with custom CA: x509 certificate signed by unknown authority

### ISSUE THREAD

**Issue by sdreger** [fluxcd/notification-controller#1083]
Environment Information:
OS: 'Linux 5.15.0-134-generic 145-Ubuntu SMP Wed Feb 12 20:08:39 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux'
kubernetes cluster: 'k3s version v1.32.2+k3s1 (381620ef); go version go1.23.6'
fluxCD: 'flux version 2.5.1'
Gitea: 'Version: 1.23.5'

I'm trying to use Gitea provider with self-hosted Gitea instance. My reverse proxy serves a self-signed certificate, so I should provide a custom CA (certificate authority) to the Provider manifest.
```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: lib-manager-go
  namespace: flux-system
spec:
  type: gitea
  address: https://gitea.private.lan/user/flux-cd-k3s
  secretRef:
    name: gitea-token
  certSecretRef:
    name: flux-system
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: lib-manager-go
  namespace: flux-system
spec:
  providerRef:
    name: lib-manager-go
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: lib-manager-go
      namespace: flux-system
```

The custom CA is in the `flux-system` secret under the `ca.crt` key:
```sh
kubectl get secret -n flux-system flux-system -o jsonpath='{ .data.ca\.crt }' | base64 -d | head -n 2
-----BEGIN CERTIFICATE-----
MIIFmTCCA4GgAwIBAgIUUZb+6uFY041w6clv+DdsuOxQtm8wDQYJKoZIhvcNAQEL
```

The Gitea secret is in the `gitea-token`:
```sh
kubectl get secret -n flux-system gitea-token -o jsonpath='{ .data.token }' | base64 -d
ea<REDACTED>ae
```

When an event is produced by the `lib-manager-go` Kustomization, I see the following error in the logs:
```json
{
    "level": "error",
    "ts": "2025-03-23T12:57:54.098Z",
    "logger": "event-server",
    "msg": "failed to dispatch notification",
    "eventInvolvedObject": {
      "kind": "Kustomization",
      "namespace": "flux-system",
      "name": "lib-manager-go",
      "uid": "54a287a0-68cc-4aa1-95f0-3b7bd0d68163",
      "apiVersion": "kustomize.toolkit.fluxcd.io/v1",
      "resourceVersion": "729862"
    },
    "Alert": {
      "name": "lib-manager-go",
      "namespace": "flux-system"
    },
    "error": "failed to initialize notifier for provider 'lib-manager-go': failed to initialize notifier: failed creating Gitea client: Get \"https://gitea.private.lan/api/v1/version\": tls: failed to verify certificate: x509: certificate signed by unknown authority"
  }
```

The error is thrown by this block:
https://github.com/fluxcd/notification-controller/blob/1967bc0c746a82e50ad88510e5617d275fba719a/internal/notifier/gitea.go#L72-L75

The client is initialized without the `TLSClientConfg`, and it is set right after the client creation (in the code block above):
https://github.com/fluxcd/notification-controller/blob/1967bc0c746a82e50ad88510e5617d275fba719a/internal/notifier/gitea.go#L77-L84

But the problem is inside the `gitea.NewClient(...)` call, because it tries to check the server version, and verify if it is greater or equal to `1.11.0`:
https://gitea.com/gitea/go-sdk/src/branch/main/gitea/client.go#L76-L81
 
In order to do that it makes an HTTP call to the: `https://gitea.private.lan/api/v1/version` endpoint. And that exact call is performed before `TLSClientConfg` is set, so it fails with the `tls: failed to verify certificate: x509: certificate signed by unknown authority` error:
https://gitea.com/gitea/go-sdk/src/branch/main/gitea/version.go#L15-L21
