### ISSUE TITLE
Feature request: Proper basic auth support for Alertmanager Provider

### ISSUE THREAD

**Issue by kalyanteja19** [fluxcd/notification-controller#1132]
Hi Team,

We are facing issue with notifications dispatch. We are trying to send flux notifications to alert manager that is enabled with basic authentication.

{"level":"debug","ts":"2025-06-24T11:51:36.214Z","logger":"events","msg":"failed to dispatch notification for Kustomization/flux-system/k8s-common-modules: failed to initialize notifier for provider 'alertmanager': failed to initialize notifier: invalid Alertmanager URL https://xxxxxx:xxxxx:alertmanager.cloud.com/api/v2/alerts/: 'parse \"https://xxx:xxxx:alertmanager.cloud.com/api/v2/alerts/\": net/url: invalid userinfo'","type":"Warning","object":{"kind":"Alert","namespace":"flux-system","name":"alertmanager-alerts","uid":"b0adf599-b7d9-4089-aabe563d156684d9","apiVersion":"notification.toolkit.fluxcd.io/v1beta3","resourceVersion":"37063594"},"reason":"NotificationDispatchFailed"}

Please be informed that **password contains special characters like @,# and tried multiple ways to escape special characters, but its not working**. Can you suggest on this issue?

**Version**
flux 2.5.1 and Kubernetes version is 1.31.8

**Comment by matheuscscp** [comment]
This is how your secret for alertmanager with basic auth should look like ([docs](https://fluxcd.io/flux/components/notification/providers/#prometheus-alertmanager)):

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-address
  namespace: default
stringData:
    address: https://<username>:<password>@<alertmanager-hostport>/api/v2/alerts/
```

Your URL is separating the basic auth part from the host with `:`, not a `@`:

```
https://xxx:xxxx:alertmanager.cloud.com/api/v2/alerts/
```
