### ISSUE TITLE
Spesifying notification Provider's namespace in an alert

### ISSUE THREAD

**Issue by ambis** [fluxcd/notification-controller#125]
Running 0.6.1

Regarding this section:
https://github.com/fluxcd/notification-controller/blob/main/config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml#L92

It only allows you to specify the name of the alert Provider, in my case discord. But it does not allow to reference it form another namespace (monitoring in this case).

The intent I believe, in a single tenant cluster, is to have only one Provider, which sits nicely in the `flux-system` namespace.

But it is impossible now to create an alert in a namespace where there are eg. HelmReleases you want to watch (like monitoring):

```
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: discord-alert-monitoring
  namespace: monitoring
spec:
  providerRef:
    name: discord
    namespace: flux-system   #  <<---- THIS IS NOT SUPPORTED
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      name: '*'
      #namespace: monitoring  # <<--- This is what I use now, when this resource is defined in the flux-system namespace, not monitoring
```

Is the intention of running all GOTK components in the `flux-system` namespace, including `Alerts`?

This issue https://github.com/fluxcd/notification-controller/issues/71 would solve my problems, since I could subscribe to all (single tenant) cluster events at once, without having to worry about setting up separate alerts per namespace.
