### ISSUE TITLE
HelmRelease errors spam slack

### ISSUE THREAD

**Issue by nomeelnoj** [fluxcd/notification-controller#158]
In setting up an alert to send to slack for `HelmRelease` objects at `error` level, it sends a ton of messages.  Here is a simple HelmRelease I applied, with an alert defined for `error`:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: broken-test
  namespace: default
spec:
  chart:
    spec:
      chart: charts/mychart
      sourceRef:
        kind: GitRepository
        name: gitops
        namespace: flux-system
  interval: 10m0s
  values:
    nothing: noone
```
This chart has a required value, so I knew this would trigger an error.  However, slack sent 22 messages within 3 seconds or so, all nearly identical.  We got 11 identical notifications for `Helm install failed` and 11 identical notifications for `reconciliation failed`.

Would it be possible to either thread these messages, or have a setting to limit number of messages within a given time frame? I could image something like this on the AlertSpec:

```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: myalert
  namespace: flux-sustem
spec:
  thread: true # For each alert, thread additional messages for the same object type/name
  notifyWindow: 
    numMessages: 1
    timeDelay: 10m0s # Allow only one notification per object per error within the given time frame
```
