### ISSUE TITLE
mTLS support for self-hosted gitlab behind cloudfare firewall

### ISSUE THREAD

**Issue by benke33** [fluxcd/notification-controller#189]
# Unable to access Gitlab API behind cloudfare firewall.

We have a self-hosted Gitlab running behind a cloudfare firewall that requires mTLS to be accessed.
Currently there's no way to specifiy certificates to be used for mTLS.
We have the option in the `Provider` to specify a `caFile`, `certFile` and `keyFile`, but only the `caFile` seems to be implemented to support self-signed certificates.

## Versions
- flux2 0.13.0
- Gitlab version 13.10.0

## Relevant manifests:

1. create provider
```
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: self-hosted-gitlab
  namespace: demo
spec:
  type: gitlab
  channel: general
  address: <self-hosted-gitlab-URL>
  secretRef:
    name: self-hosted-gitlab
```
2. create alert
```
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: sample
  namespace: demo
spec:
  providerRef:
    name: self-hosted-gitlab
  eventSeverity: info
  summary: "some summary"
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: sample
      namespace: demo
---
```
3. create secret with gitlab token
```
---
apiVersion: v1
kind: Secret
metadata:
  name: self-hosted-gitlab
  namespace: cd
data:
  token: <redacted>
---
```

## Relevant logs:

Error from notification-controller:
```
{
  "level": "info",
  "ts": "2021-04-26T07:35:08.088Z",
  "logger": "event-server",
  "msg": "Dispatching event: Update completed",
  "reconciler kind": "Kustomization",
  "name": "aws-sample",
  "namespace": "demo"
}
{
  "level": "error",
  "ts": "2021-04-26T07:35:08.414Z",
  "logger": "event-server",
  "msg": "failed to send notification",
  "reconciler kind": "Kustomization",
  "name": "aws-sample",
  "namespace": "demo",
  "error": "invalid character '<' looking for beginning of value"
}
```

## Notes

Accessing the Gitlab API using `curl` and specifying the certificates with `--cert` and `--key` works fine.
