### ISSUE TITLE
Support MatterMost

### ISSUE THREAD

**Issue by makeacode** [fluxcd/notification-controller#203]
We use mattermost (slack clone) in our enterprise and after much debugging using the slack provider i discovered the code does not contain the recently added logic to handle self-signed certificates.

Can this please be added in a future release?

**Comment by almorgv** [comment]
Seems like we stuck at this problem too.

```
kubectl -n flux-system create secret generic mattermost-url --from-literal=address=<WEBHOOK_URL>
```
```
echo -n | openssl s_client -connect mattermost.local:443 -showcerts | sed -ne "/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p" > mm.pride.local.crt
kubectl -n flux-system create secret generic mattermost-certs --from-file=caFile=mattermost.local.crt
```

```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: mattermost
  namespace: flux-system
spec:
  type: mattermost
  channel: general
  secretRef:
    name: mattermost-url
  certSecretRef:
    name: mattermost-certs
```


```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: default-notifications
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: HelmRepository
      name: '*'
    - kind: Kustomization
      name: '*'
```
notification-controller logs
```
{"level":"error","ts":"2021-06-04T07:34:20.054Z","logger":"event-server","msg":"failed to send notification","reconciler kind":"Kustomization","name":"flux-system","namespace":"flux-system","error":"*****p*****o*****s*****t*****M*****e*****s*****s*****a*****g*****e***** *****f*****a*****i*****l*****e*****d*****:***** *****f*****a*****i*****l*****e*****d***** *****t*****o***** *****e*****x*****e*****c*****u*****t*****e***** *****r*****e*****q*****u*****e*****s*****t*****:***** *****P*****O*****S*****T***** ...*****:***** *****x*****5*****0*****9*****:***** *****c*****e*****r*****t*****i*****f*****i*****c*****a*****t*****e***** *****s*****i*****g*****n*****e*****d***** *****b*****y***** *****u*****n*****k*****n*****o*****w*****n***** *****a*****u*****t*****h*****o*****r*****i*****t*****y*****"}
```
That says `postMessage failed: failed to execute request: POST ...: x509: certificate signed by unknown authority`
