### ISSUE TITLE
Permanently repeated Kustomization states in Gitlab

### ISSUE THREAD

**Issue by fgunited** [fluxcd/notification-controller#212]
### Issue description

We are using an Gitlab-Provider + Kustomization-Alert on Git- or Helm-Resources.
The Kustomization object has a reconcilation interval of 5 minutes; every 5 minutes I get an “Update completed” Event from the Kustomization object, which then creates a Gitlab Job Result: 

![flux_issue1](https://user-images.githubusercontent.com/11735950/122549565-edb5f800-d032-11eb-9ee4-817b1212d5b5.png)

**Not working as expected**:  We expect, that only on change of state or a new commit a git job as feedback will be put to Gitlab.

Using Notification-Controller v0.15.0, v0.14.0

### Steps to reproduce the issue

Creating a **kustomiziation**, like e.g.:
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-deployment-kustomization-dev-default
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: k-testnamespace--demo-service
  namespace: flux-system
spec:
  healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v1beta1
    kind: HelmRelease
    name: demo-service
    namespace: testnamespace
  interval: 5m
  path: ./manifests/testnamespace
  prune: true
  sourceRef:
    kind: GitRepository
    name: g-testnamespace--demo-service
    namespace: flux-system
  targetNamespace: testnamespace
```

An **provider**:
```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-deployment-kustomization-dev-default
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: p-testnamespace--demo-service
  namespace: flux-system
spec:
  address: GITLABREPOSITORYURL
  secretRef:
    name: secret-token
  type: gitlab
```

An alert:
```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-deployment-kustomization-dev-default
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: a-testnamespace--demo-service
  namespace: flux-system
spec:
  eventSeverity: info
  eventSources:
  - kind: Kustomization
    name: k-testnamespace--demo-service
    namespace: flux-system
  providerRef:
    name: p-testnamespace--demo-service
  suspend: false
```

### What's the expected result?
Only on change of state or a new commit will be put as feedback to Gitlab.

### What's the actual result?
Every reconcilation-interval  a new state will be shown in the specific gitlab-repository.

#### Log snippets
![image](https://user-images.githubusercontent.com/11735950/122550651-37eba900-d034-11eb-9ef4-57fc525bb61e.png)
![image (1)](https://user-images.githubusercontent.com/11735950/122550718-489c1f00-d034-11eb-83e8-32ee2e58fd40.png)

#### Some further thoughts
The method in https://github.com/fluxcd/notification-controller/blob/main/internal/notifier/gitlab.go#L94 will be called on every reconcilation-event by the provider, in the documentation of Gitlab https://docs.gitlab.com/ce/api/commits.html#post-the-build-status-to-a-commit it is mentioned that these "Adds or updates a build status of a commit." - But I think that also an "Update" of the build status will be shown as "retried" in above gitlab job statues. 

**For example in the Github Provider** you can see in https://github.com/fluxcd/notification-controller/blob/main/internal/notifier/github.go#L125 that at first will be checked, if such kind of status is already present to github and if so the event will be dropped. => Perhaps we need the same mechanism for Gitlab?
