### ISSUE TITLE
Single github receiver per cluster

### ISSUE THREAD

**Issue by yawboateng** [fluxcd/notification-controller#214]
is it possible to  have a single receiver handle every resource type in a specific namespace (or every namespace)? 

so I don't have to generate and manually add multiple webhooks to github for every single application or even if i was using 1 receiver, I don't want to have remember to update this file every time someone deploys a new application? 

something like:

```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: github-notification
  namespace: flux-system
spec:
  type: github
  events:
    - "ping"
    - "push"
  secretRef:
    name: notification-webhook-receiver-token
  resources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
    - kind: HelmRelease
      name: '*'
    - kind: HelmRepository
      name: '*'
    - apiVersion: 
      kind: HelmChart
      name: '*'
```

or will it be possible for flux to automatically add/remove the webhook urls in github? - so every time you create a new receiver, you dont manually have to update github?

currently i get this error:
```
{"level":"error","ts":"2021-07-02T20:35:02.396Z","logger":"receiver-server","msg":"unable to annotate resource 'Kustomization/*.'","reconciler kind":"Receiver","name":"github-notification","namespace":"flux-system","error":"unable to read Kustomization 'flux-system/*' error: kustomizations.kustomize.toolkit.fluxcd.io \"*\" not found"}
{"level":"error","ts":"2021-07-02T20:35:02.399Z","logger":"receiver-server","msg":"unable to annotate resource 'HelmRelease/*.'","reconciler kind":"Receiver","name":"github-notification","namespace":"flux-system","error":"unable to read HelmRelease 'flux-system/*' error: helmreleases.helm.toolkit.fluxcd.io \"*\" not found"}
{"level":"error","ts":"2021-07-02T20:35:02.407Z","logger":"receiver-server","msg":"unable to annotate resource 'HelmRepository/*.'","reconciler kind":"Receiver","name":"github-notification","namespace":"flux-system","error":"unable to read HelmRepository 'flux-system/*' error: helmrepositories.source.toolkit.fluxcd.io \"*\" not found"}
{"level":"error","ts":"2021-07-02T20:35:02.407Z","logger":"receiver-server","msg":"unable to annotate resource 'HelmChart/*.'","reconciler kind":"Receiver","name":"github-notification","namespace":"flux-system","error":"apiVersion must be specified for kind 'HelmChart'"}
```
