### ISSUE TITLE
Helmrelease doesnt update after a new push to github

### ISSUE THREAD

**Issue by yawboateng** [fluxcd/notification-controller#215]
So, i have a helmrlease that gets its values from a configmap and i also have this github receiver:

```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: github-notification
  namespace: flux-system
spec:
  type: github
  events:
    - "push"
  secretRef:
    name: notification-webhook-receiver-token
  resources:
    - kind: GitRepository
      name: flux-system
```

but when i make changes to the configmap, and push to github, it doesnt reconcile the helm release immediately. i see the changes in the configmap within the k8s cluster but it doesnt in-turn trigger the helmrelease to reconcile with the new values
