### ISSUE TITLE
Channel Name with Spaces return 404

### ISSUE THREAD

**Issue by jhramey** [fluxcd/notification-controller#228]
I am able to post to channels without spaces but when I change the channel to one with spaces, I get the following error in the notification controller logs:
```
"error":"postMessage failed: request failed with status code 404, {\"id\":\"web.incoming_webhook.channel.app_error\",\"message\":\"Couldn't find the channel.\",\"detailed_error\":\"\",\"request_id\":\"6c9sc8s3mpnj5nr9usupbjd39h\",\"status_code\":404}"}
```

Provider File:
```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
  kind: Provider
  metadata:
    name: mattermost
    namespace: flux-system
  spec:
    channel: 'Flux Cluster Notifications'
    secretRef:
      name: mattermost-url
    type: slack
```

Flux info:
`flux version 0.16.1`
```
[jhramey@ip-10-117-131-46 base]$ flux check
► checking prerequisites
✗ flux 0.16.1 <0.16.2 (new version is available, please upgrade)
✔ kubectl 1.21.3 >=1.18.0-0
✔ Kubernetes 1.20.2 >=1.16.0-0
► checking controllers
✔ all checks passed
```
