### ISSUE TITLE
Github Notifier

### ISSUE THREAD

**Issue by phillebaba** [fluxcd/notification-controller#26]
The Github Notifier given an event containing revision metadata it updates the commit status in a Github repository.

The notifier would be configured in a similar manner as the other notifiers. With some small differences. The address given in the provider would have be the address of the Github repository. Aditionally the provider requires a secret ref to be given the personal access token to communicate with Github. The Alert would need to explicitly specify the resources to react upon as the source repository they are reconciled with have to match the repository of the provider. Another solution would be if we could get the source repository of the involved object and match it to a provider with the same repository, but that would go against the current behavior of the notifier.
```yaml
apiVersion: notification.fluxcd.io/v1alpha1
kind: Provider
metadata:
  name: podinfo-gh-status
  namespace: gitops-system
spec:
  type: github-commit-status
  address: https://github.com/stefanprodan/podinfo # repo URL
  secretRef:
    name: github-token # GH token with 'repo:status' scope
---
apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: gitops-system
data:
  token: <token>
---
apiVersion: notification.fluxcd.io/v1alpha1
kind: Alert
metadata:
  name: podinfo-status-update
  namespace: gitops-system
spec:
  providerRef: 
    name: podinfo-gh-status 
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: webapp-backend
---
apiVersion: kustomize.fluxcd.io/v1alpha1
kind: Kustomization
metadata:
  creationTimestamp: null
  name: webapp-backend
  namespace: gitops-system
spec:
  dependsOn:
  - webapp-common
  healthChecks:
  - kind: Deployment
    name: backend
    namespace: webapp
  interval: 10m0s
  path: ./deploy/webapp/backend
  prune: true
  sourceRef:
    kind: GitRepository
    name: webapp
  timeout: 2m0s
  validation: client
status: {}
```

An detail in this implementation is that if the Kustomization resource and the source repoisitory sepcified are not the same. The event revision relates to the source repository given in the Kustomization resource, and not the repository the Kustomization resource originates from.
