### ISSUE TITLE
Feature Request: Selector-like Config Options for Alert CRD Based on Label

### ISSUE THREAD

**Issue by shin-go** [fluxcd/notification-controller#275]
Per the current documentation on the [Alert CRD](https://fluxcd.io/docs/components/notification/alert/), when configuring multiple `EventSources` you must manually enumerate each CRD type and name. Since manually configuring things is something few want to do for very long or at scale, introducing a selector-like option for Alerts could be useful - particularly if it can be based off Labels on the specified `EventSource` kind.

My particular use case for this is that we have multiple dev teams who own multiple microservices. We have each microservice reconciling via a Kustomization specifically for that service (ex.: configrepo/dev-us-west-2/microfoo/, configrepo/dev-us-west-2/microbar/). In order for the wildcard pattern to work, we would need each miroservice subdir in the config repo to be prefixed with a team identifier; or move the subdirs around such that all microservices owned by a particular team is in a subdir for that team (e.g.: `configrepo/dev-us-west-2/foobar/micro[foo|bar]`). While the latter approach *could* work, ownership or dissolution of the team could change down the road.

In this case, relying on Labels on the Kustomization, etc. CRDs to assert ownership wouldn't require much change and is maintainable into the future. A mock of such configuration might look like:

```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: team-foobar-kustomizations
  namespace: default
spec:
  providerRef: 
    name: dev-msteams
  eventSeverity: error
  eventSources:
    - kind: Kustomization
      namespace: default
      selector:
        kind: [name|label]
        value: 'owner: foobar' # or literal/wildcard as docs currently stand if kind: name
```

**Comment by stefanprodan** [comment]
I propose we add new optional field to the `EventSource` named `matchLabels` of type `map[string]string`. The selector will be taken into consideration only if `name` is set to `*`. This would not break the current API, and will allow filtering of objects of a particular Kind within a namespace based on labels.

This selects all GitRepos and Kustomizations in the `default` namespace:

```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: all
  namespace: default
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: "*"
    - kind: Kustomization
      name: "*"
```

This selects all GitRepos and Kustomizations in the `default` namespace that have the `team: dev` and `env: staging` labels:

```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: all
  namespace: default
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: "*"
      matchLabels:
        team: dev
        env: staging
    - kind: Kustomization
      name: "*"
      matchLabels:
        team: dev
        env: staging
```
