### ISSUE TITLE
Revision string format incorrect

### ISSUE THREAD

**Issue by callaertanthony** [fluxcd/notification-controller#311]
Hi,

I encounter this error on notification sending :
```
"error":"Revision string format incorrect: 1.8.0+1"
```

This happens because override the version and adds a "since time" value when it's listening on a branch source to be able to correlate new changes from the branch.
This is what this PR did : [](https://github.com/fluxcd/source-controller/pull/172/files)

So, it should be great to update the current parsing strategy to be able to handle this native feature of `GitRepository` source.

Moreover, I don't understand why notification controller do this role of check the version for which he would like to send notification ? In my opinion this is not the responsibility of a notification tool.

**Comment by SomtochiAma** [comment]
Hey @callaertanthony , 
Please, How can I reproduce this bug on my end?.

**Comment by callaertanthony** [comment]
Hi @SomtochiAma, @stefanprodan,

@stefanprodan, thanks for your answer and explanation about revision management. Do you confirm this is a pattern matching bug from notification controller and not a bad management from my side ?

@SomtochiAma, this bug happens on my side having a helm packaged chart managed by flux from a `GitRepository`. Flux adds a timestamp value after the chart version (the `+1`). `1.8.0` from the git repository chart become `1.8.0+1`

I use my chart from git repository source on a helm release like this :
```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: my-chart-helm-repo
...
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-release
spec:
  interval: 1m
  timeout: 10m
  chart:
    spec:
      chart: .
      sourceRef:
        kind: GitRepository
        name: my-chart-helm-repo
        namespace: flux-system
...
```

So I see two (maybe more) possibilities to reproduce this :
* use a chart from a `GitRepository` to let flux packaging it (I also tried with a fixed tag value into the `GitRepository` the `+1` is added too)
* build a chart with a fixed bug version (with a `+[n]` on your side and use it as a helm chart source

My alert is a simple github alert :
```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: github-release-alert
spec:
  providerRef:
    name: github
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      name: '*'
```
