### ISSUE TITLE
Generic Provider alert not adding Authorization header for id:password

### ISSUE THREAD

**Issue by naustin** [fluxcd/notification-controller#312]
I'm attempting to send Flux alerts to Elastic using the 'generic' Provider event but I'm seeing http 401 returned from Elastic for the notification requests being sent.   I've configured linkerd to monitor the requests and it looks like the authorization header is not being added to the 'generic' Provider request message.   I'm providing the Elastic URL and credentials using a secret with 'address' and 'token'  values.

Here's my Provider configuration:
```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: flux-alerts-to-elastic
  namespace: flux-system
spec:
  secretRef:
    name: elastic-token
  type: generic

```

Here's my elastic-token sealed secret:
```
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: elastic-token
  namespace: flux-system
spec:
  encryptedData:
    address: <elastic url>
    token: <id:password>
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: elastic-token
      namespace: flux-system
```
