### ISSUE TITLE
Matrix: Can't get CertSecretRef working

### ISSUE THREAD

**Issue by Nold360** [fluxcd/notification-controller#316]
Hi,

I'm trying to get the matrix notification provider work with a custom CA certificate, but I can't seem to get it working. Even if it's using the same CA-Chain as my gitlab repository, I'm reconciling from.  My secret contains the key 'caFile' with a valid cert chain.

Here is my controller config:
``` yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: matrix-provider
  namespace: flux-system
spec:
  type: matrix
  #username: flux_notifications
  address: https://matrix.domain.com
  channel: "!Vahj...."
  secretRef:
    name: matrix-secret
  certSecretRef:
    name: mydomain-tls
```

I can see the certificate being accepted by the controller. But once it tries to send a notification i get:
```
2022-01-26T07:02:35.018Z error Kustomization/infrastructure.flux-system - failed to send notification postMessage failed: failed to execute request: PUT https://matrix.domain.com/_matrix/client/r0/rooms/!Vahjhpt..../send/m.room.message/59f8607e383312890fe3662a338914cefece21a2 giving up after 1 attempt(s): Put &#34;https://matrix.domain.com/_matrix/client/r0/rooms/!Vahj...../send/m.room.message/59f8607e383312890fe3662a338914cefece21a2&#34;: x509: certificate signed by unknown authority
```

I tied using the same chain I used for bootstrapping, is saved by flux as secret `flux-system` & used successfully for the `GitRepository` source. 

IDK what else to try, could  someone help me out?

Versions:
```
flux: v0.25.3
helm-controller: v0.15.0
kustomize-controller: v0.19.1
notification-controller: v0.20.1
source-controller: v0.20.1
```

//Edit:
It seems to me like the CertPool is not forwarded to the Matrix notifier? https://github.com/fluxcd/notification-controller/blob/12c8c87d93637e2a8dd9455fbb08322e611fffd9/internal/notifier/factory.go#L85
