### ISSUE TITLE
azdevops - "could not list commit statuses: Request returned status: 401 Unauthorized"

### ISSUE THREAD

**Issue by MarkStromme** [fluxcd/notification-controller#374]
The notification controller fails to send notification because its unauthorised.

I have followed the documentation and created secret called azdevops (the PAT token has full access to everything):

```
apiVersion: v1
kind: Secret
metadata:
  name: azuredevops
data:
  token: <base64 encoded PAT token>
``` 

I have an alert and provider defined like this in "some-namespace" namespace:

```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: test
  namespace: some-namespace
spec:
  type: azuredevops
  address: https://dev.azure.com/<org>/<projectx>/_git/<repository>
  secretRef:
    name: azuredevops
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: test
  namespace: some-namespace
spec:
  providerRef:
    name: test
  eventSeverity: info
  eventSources:
  - kind: Kustomization
    name: some-kustomization
    namespace: some-namespace
```

"some-kustomization" kustomization:
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: some-kustomization
  namespace: some-namespace
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: some-repository
  path: ./apps/base/some-namespace
  prune: true
```

For some reason there were no updates on the commit statuses in Azure DevOps repo.
This is the log from notification controller when I trigger "some-kustomization" to reconcile:
```
{"level":"error","ts":"2022-05-13T06:45:17.591Z","logger":"event-server","msg":"failed to send notification","reconciler kind":"Kustomization","name":"some-kustomization","namespace":"some-namespace","error":"could not list commit statuses: Request returned status: 401 Unauthorized"}
```

I have tried to make this work for couple of days now without any luck... Any thoughts?
