### ISSUE TITLE
alert.spec.summary not showing on slack messages for GitRepository events.

### ISSUE THREAD

**Issue by fawadasaurus** [fluxcd/notification-controller#391]
I am getting a "summary" for my `Kustomization` messages.  I am not getting a summary for my `GitRepository` messages.
```
gitrepository/flux-system.flux-system
stored artifact for commit 'Merge pull request #18 from repo/flux-alert-...'
revision
main/b7cdff731fcf18118c235ebeafe9e9bf5e4a18e7
```
```
kustomization/flux-system.flux-system
Alert/flux-system/flux-slack-notifier configured
revision
main/b7cdff731fcf18118c235ebeafe9e9bf5e4a18e7
summary
prod-aks Cluster
```

Here is my config.
```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: flux-slack-notifier
  namespace: flux-system
spec:
  summary: "prod-aks Cluster"
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
```
