### ISSUE TITLE
Unable to parse `package` event from GitHub webhook

### ISSUE THREAD

**Issue by imle** [fluxcd/notification-controller#393]
Error message I get when the webhook comes in.

`unable to parse GitHub payload, err: json: cannot unmarshal object into Go struct field PackageVersion.package.package_version.body of type string`.

Trying to use this with the image watcher.

`v0.22.2`

**Comment by somtochiama** [comment]
Can you give more information on how you created the Github webhook?

**Comment by kingdonb** [comment]
I created a Receiver such as this one:

```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: podinfo-package
  namespace: podinfo-flux-oci
spec:
  events:
  - package
  - ping
  resources:
  - kind: OciRepository
    name: podinfo
    namespace: podinfo-flux-oci
  secretRef:
    name: webhook-token
  type: github
```
![Screen Shot 2022-08-09 at 4 41 23 PM](https://user-images.githubusercontent.com/3286998/183757325-d989721f-5ed9-460a-85a6-9b16d57ea087.png)

and set the GitHub events to `ping` and `package`, which corresponds to the `Package` event in GitHub (above)

I wound up using this resource target instead, as the `OciRepository` target is not allowed yet per #400 – this:

```
  resources:
  - kind: Kustomization
    apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
    name: podinfo-oci
    namespace: podinfo-flux-oci
```

The result in the notification controller logs was as reported above,

```
{"level":"info","ts":"2022-08-09T20:43:31.762Z","logger":"receiver-server","msg":"handling request: ea93a12235526ba1ffd5366bd0ed06ab6707dce300b846515044ecfc2e24edc4"}
{"level":"error","ts":"2022-08-09T20:43:31.803Z","logger":"receiver-server","msg":"unable to validate payload","reconciler kind":"Receiver","name":"podinfo-package","namespace":"podinfo-flux-oci","error":"unable to parse GitHub payload, err: json: cannot unmarshal object into Go struct field PackageVersion.package.package_version.body of type string"}
```

Compare with the successful version, that just receives and responds to `push` (and does not have a parse failure):
```
{"level":"info","ts":"2022-08-09T20:40:52.226Z","logger":"receiver-server","msg":"handling request: ea93a12235526ba1ffd5366bd0ed06ab6707dce300b846515044ecfc2e24edc4"}
{"level":"info","ts":"2022-08-09T20:40:52.227Z","logger":"receiver-server","msg":"handling GitHub event: push","reconciler kind":"Receiver","name":"podinfo-package","namespace":"podinfo-flux-oci"}
{"level":"info","ts":"2022-08-09T20:40:52.336Z","logger":"receiver-server","msg":"resource 'Kustomization/podinfo-oci.podinfo-flux-oci' annotated","reconciler kind":"Receiver","name":"podinfo-package","namespace":"podinfo-flux-oci"}
```

We should definitely try to make this work for use with the Flux OCI support, it will be more important IMHO for driving OCIRepository targets than it was for use with ImageRepository resources, but I think this can still be used for both 👍 

Webhooks for a GHCR Package are configured on the Git Repository that the OCI repository is seeded from. Screenshot above should help to reproduce this.
