### ISSUE TITLE
OCIRepository type should be allowed in Receiver spec

### ISSUE THREAD

**Issue by kingdonb** [fluxcd/notification-controller#400]
I see that OCIRepository type is an allowed event source in [0.25.0](https://github.com/fluxcd/notification-controller/blob/6f729e491b6709c7ff007e9098b1002a398c226a/CHANGELOG.md#0250)

OCIRepository should also be added as an allowed target for receiver, but it looks like it has not yet. (Will this be possible to include before the final release?)

I tried it just now with the latest commit from the `oci` branch, that appears to include this latest notification controller release, and just to confirm it does look like that needs to be added:

```
flux-system        flux-system        6d18h   False     Receiver/podinfo-flux-oci/podinfo-package dry-run failed, reason: Invalid, error: Receiver.notification.toolkit.fluxcd.io "podinfo-package" is invalid: spec.resources.kind: Unsupported value: "OciRepository": supported values: "Bucket", "GitRepository", "Kustomization", "HelmRelease", "HelmChart", "HelmRepository", "ImageRepository", "ImagePolicy", "ImageUpdateAutomation"...
```

This is my Receiver:

```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: podinfo-package
  namespace: podinfo-flux-oci
spec:
  events:
  - package
  - ping
  resources:
  - kind: OciRepository
    name: podinfo
    namespace: podinfo-flux-oci
  secretRef:
    name: webhook-token
  type: github
```

I am uncertain whether `package` webhooks work with any other target, I will test that next. From a quick search of the open issues, signs point to no:

* https://github.com/fluxcd/notification-controller/issues/393
