### ISSUE TITLE
Unable to list commit statuses

### ISSUE THREAD

**Issue by marcuslindfeldt** [fluxcd/notification-controller#415]
Hello we are evaluating flux and are looking into setting up the github status integration however it does not seem to work.

I tried it on my personal account and it worked fine but in our github organization it does not work. I have verified that the PAT is able to list commit statuses via the gh api so I dont think its an authentication issue.

notification-controller logs:
```
{"level":"error","ts":"2022-09-08T14:32:17.181Z","logger":"event-server","msg":"failed to send notification","reconciler kind":"Kustomization","name":"infrastructure","namespace":"flux-system","error":"could not list commit statuses: context canceled"}
```

Manifests:
```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: flux-system
  namespace: flux-system
spec:
  type: github
  address: https://github.com/<org>/<repo>
  secretRef:
    name: github
```

Note! This secret has `token` as key with the github PAT as value.

```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: github-notifications
  namespace: flux-system
spec:
  providerRef:
    name: flux-system
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: "*"
      namespace: flux-system
```

What am I missing?
