### ISSUE TITLE
Unable to trigger generic-hmac receiver

### ISSUE THREAD

**Issue by havard024** [fluxcd/notification-controller#440]
Hi,

I'm trying to setup a generic-hmac receiver to receive webhooks from aws ECR when new images are pushed so I can trigger image update automation

For now I've setup a receiver

```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: supermario-ecr
  namespace: flux-system
spec:
  type: generic-hmac
  secretRef:
    name: supermario-ecr-receiver
  resources:
    - kind: ImageRepository
      name: supermario
      namespace: flux-system
```

The receiver has been initialized

```
flux get receiver supermario-ecr
NAME                    SUSPENDED       READY   MESSAGE                                                                                               
supermario-ecr                False           True    Receiver initialized with URL: /hook/9fa82...377c
```

I'm trying to trigger the webhook manually using python without any luck

```
import hmac, hashlib, requests
secret = '...'
data = 'request body'
signature = hmac.new(key=bytes(secret, 'utf-8'), msg=bytes(data, 'utf-8'), digestmod=hashlib.sha256)
requests.post('https://webhook.test.juridika.no/hook/9fa82...377c', data=data, headers={'X-Signature': f'sha256={signature.hexdigest()}'})
```

The response is 202 and only thing I can see in the notification controller logs is 

```
{"level":"info","ts":"2022-11-13T21:17:39.450Z","logger":"event-server","msg":"Discarding event, no alerts found for the involved object","reconciler kind":"","name":"","namespace":""}
```

**Comment by kingdonb** [comment]
The log message at the end does not seem to be related to receivers:

https://github.com/fluxcd/notification-controller/blob/main/internal/server/event_handlers.go#L113

(It comes from the event handler, which is not related to the receiver)

It looks like the `Receiver` is `Ready` – the 202 indicates that the Receiver received your request, are you certain that it did not work? The effect of receiving the webhook is supposed to be a `reconcile` gets triggered on the target object. Can you `kubectl get imagerepositories -w` and check if it is indeed being reconciled when you send the webhook request?

Could you also let us know what version of Flux is installed, and what version of Kubernetes? The log message is strange, it should not have an empty "name" or "namespace" – so we're curious what other resources in the Notification Controller's APIs you might have on the cluster, (like Providers or Alerts) – one of them could have created this message?

**Comment by havard024** [comment]
thanks for looking into this

I also agree that the log message should not be related to the receivers, but it gets triggered right after the hook is triggered 🤷 

I changed the generic hmac receiver to reconcile flux-system git repository instead, push an empty commit up, trigger the webhook, but nothing except that mystical log message from notification controllers. In the end I run a manual flux reconcile to show that the git repository is getting updated.

I've made a video of my attempt here https://www.loom.com/share/d55582ec3a8c4d748a091c3b3ff0cc5d

flux version
```
$flux version
flux: v0.34.0
helm-controller: v0.26.0
image-automation-controller: v0.26.1
image-reflector-controller: v0.22.1
kustomize-controller: v0.30.0
notification-controller: v0.28.0
source-controller: v0.31.0
```

kubernetes version
```
$kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:17:57Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.13-eks-fb459a0", GitCommit:"55bd5d5cb7d32bc35e4e050f536181196fb8c6f7", GitTreeState:"clean", BuildDate:"2022-10-24T20:35:40Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```

alerts
```
$flux get alerts
NAME                    SUSPENDED       READY   MESSAGE     
gitlab-flux-alerts      False           True    Initialized     
slack-flux-alerts       False           True    Initialized     
```

and their manifests

```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: slack-flux-alerts
  namespace: flux-system
spec:
  providerRef:
    name: slack-flux-alerts
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
    - kind: HelmRelease
      name: '*'
    #- kind: ImagePolicy
    #  name: '*'
    - kind: ImageRepository
      name: '*'
    - kind: ImageUpdateAutomation
      name: '*'
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: gitlab-flux-alerts
  namespace: flux-system
spec:
  providerRef:
    name: flux-system
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: '*'
```

alert providers
```
$flux get alert-providers
NAME                    READY   MESSAGE     
flux-system             True    Initialized     
slack-flux-alerts       True    Initialized     
```

and their manifests

```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: slack-flux-alerts
  namespace: flux-system
spec:
  type: slack
  channel: #debug-alerts"
  secretRef:
    name: slack-flux-webhook
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: flux-system
  namespace: flux-system
spec:
  type: gitlab
  address: https://gitlab.com/...
  secretRef:
    name: flux-system-pat
```

**Comment by havard024** [comment]
After further testing, the issue we are experiencing seems to happen on our gitlab webhooks as well, it's probably not directly connected to the generic hmac receiver.

Below I've attached the past 7 days of logs from our test cluster matching these mysterious log messages

the log message
```
{"level":"info","ts":"2022-12-03T09:52:54.956Z","logger":"event-server","msg":"Discarding event, no alerts found for the involved object","reconciler kind":"","name":"","namespace":""}
```
past 7 days of logs
<img width="1569" alt="Screenshot 2022-12-03 at 10 51 44" src="https://user-images.githubusercontent.com/2212037/205434985-fefbf44e-dbc9-4227-b5da-b223f133617e.png">
detailed logs from one of the logs above
<img width="846" alt="Screenshot 2022-12-03 at 10 51 51" src="https://user-images.githubusercontent.com/2212037/205434988-a70becc8-57b6-43e2-894b-4bc1da250d47.png">

Here is a video sending webhooks from gitlab to our test cluster showing that this log message occurs from that webhook

https://www.loom.com/share/3829177d4255494bb6b5c8b9ce937bdb

We have multiple other gitlab repos where the webhook are not working as expected, reconciliation is not triggered and we get the mysterious log message.

Here's the output of `flux check`
```
> flux check
► checking prerequisites
✗ flux 0.34.0 <0.37.0 (new version is available, please upgrade)
✔ Kubernetes 1.23.13-eks-fb459a0 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.26.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.26.1
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.22.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.30.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.28.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.31.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta1
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta1
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta1
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta1
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed
```

**Comment by havard024** [comment]
I found the issue for why the webhooks was not triggered anymore, it was a misconfiguration on our side when exposing the webhook receiver endpoint outside the cluster.

We had exposed the webhook receiver using istios VirtualService to the notification controller on port 80 as shown below

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: flux-system-webhook
  namespace: flux-system
spec:
  gateways:
  - ...
  hosts:
  - ...
  http:
  - route:
    - destination:
        host: notification-controller
        port:
          number: 80
```

instead of sending the traffic directly to the `webhook-receiver` service

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: flux-system-webhook
  namespace: flux-system
spec:
  gateways:
    - ...
  hosts:
    - ...
  http:
    - route:
        - destination:
            host: webhook-receiver
```

We now see the following logs for notification controller when triggering webhooks

```
{
	"level": "info",
	"ts": "2023-01-01T03:07:08.050Z",
	"logger": "receiver-server",
	"msg": "handling GitLab event: Push Hook",
	"reconciler kind": "Receiver",
	"name": "flux-system",
	"namespace": "flux-system"
}
```

and the below cryptic messages have disappeared

```
{
	"level": "info",
	"ts": "2022-11-13T21:17:39.450Z",
	"logger": "event-server",
	"msg": "Discarding event, no alerts found for the involved object",
	"reconciler kind": "",
	"name": "",
	"namespace": ""
}
```

I'm going ahead an closing this issue, sorry if this has caused any inconvenience on your end
