### ISSUE TITLE
Alerts duplicate error messages in slack channel

### ISSUE THREAD

**Issue by dimakyriakov** [fluxcd/notification-controller#445]
**Problem:**
I created an alert to monitor all helmreleases in a specific namespace and it's making huge traffic of errors in a slack channel.
It duplicates errors every certain period and alerting despite no changes to helmreleases.

**Here is alert file:**
```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: integration
  namespace: flux-system
spec:
  summary: "integration"
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      namespace: integration
      name: '*'
```

**Question:**
Is it possible to trigger an alert only if we made changes to helmrelease, not the status of an existing one?
Is it possible to not duplicate alert message that we already received after certain period of the time?

**Comment by dimakyriakov** [comment]
![image](https://user-images.githubusercontent.com/96116626/203517297-c3bcad14-8073-419e-9f20-b6be145a0e7e.png)
some of our helmreleases has error "reconciliation failed: install retries exhausted" and mostly we are ok with it
it would be nice to only get this error once when it appears

**Comment by stefanprodan** [comment]
@dimakyriakov by design, error alerts are sent every 5 minutes until they are resolved. You can increase the internal with the -`--rate-limit-interval`, flags docs here https://fluxcd.io/flux/components/notification/options/

**Comment by dimakyriakov** [comment]
thank you for response Guys, i will close the ticket

**Comment by dimakyriakov** [comment]
@stefanprodan, hey, i just want to ask where exactly I can set `--rate-limit-interval` option?
I created provider and alert in yaml file. For me it looks like it's options for cli.

**Comment by stefanprodan** [comment]
That’s a controller flag, see here how to change them https://fluxcd.io/flux/cheatsheets/bootstrap/

**Comment by dimakyriakov** [comment]
This is my kustomization.yaml file. You mean I have to increase `--rate-limit-interval` for name: notification-controller?

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patchesStrategicMerge:  # these are tuned for demonstration and debugging
- |-
  apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
  kind: Kustomization
  metadata:
    name: flux-system
    namespace: flux-system
  spec:
    patches:
    - target:
        version: v1
        group: apps
        kind: Deployment
        name: notification-controller
        namespace: flux-system
      patch: |-
        - op: add
          path: /spec/template/spec/containers/0/args/-
          value: --rate-limit-interval=10s  # do not discard messages that are sent again after 10s+
    - target:
        version: v1
        group: apps
        kind: Deployment
        name: kustomize-controller
        namespace: flux-system
      patch: |-
        - op: add
          path: /spec/template/spec/containers/0/args/0
          value: --concurrent=5             # increase the number of Kustomizations processed at once
        - op: replace
          path: /spec/template/spec/containers/0/resources/limits/cpu
          value: "2"                        # allow KC access to more CPU
        - op: replace
          path: /spec/template/spec/containers/0/resources/limits/memory
          value: "2Gi"                      # allow KC access to more memory
    - target:
        version: v1
        group: apps
        kind: Deployment
        name: source-controller
        namespace: flux-system
      patch: |-
        - op: replace
          path: /spec/template/spec/containers/0/resources/limits/cpu
          value: "2"                        # allow KC access to more CPU
        - op: replace
          path: /spec/template/spec/containers/0/resources/limits/memory
          value: "2Gi"                      # allow KC access to more memory
    - target:
        version: v1
        group: apps
        kind: Deployment
        name: helm-controller
        namespace: flux-system
      patch: |-
        - op: add
          path: /spec/template/spec/containers/0/args/0
          value: --concurrent=12             # increase the number of HelmReleases processed at once
        - op: replace
          path: /spec/template/spec/containers/0/resources/limits/cpu
          value: "2"                        # allow KC access to more CPU
        - op: replace
          path: /spec/template/spec/containers/0/resources/limits/memory
          value: "2Gi"                      # allow KC access to more memory
```
