### ISSUE TITLE
3rd-party controller notifications

### ISSUE THREAD

**Issue by dcfranca** [fluxcd/notification-controller#464]
I'm trying to setup notifications from `tf-controller`, so I followed what is mentioned [here](https://fluxcd.io/flux/cheatsheets/bootstrap/#enable-notifications-for-third-party-controllers)

I'm not sure if this falls here, or better on `tf-controller`... but my guess is that I'm just misconfiguring something

I have checked the resources and they seem to contain the correct patches:

```
kubectl -n flux-system describe crd alerts.notification.toolkit.fluxcd.io
...
                    Kind:
                      Description:  Kind of the referent
                      Enum:
                        Bucket
                        GitRepository
                        Kustomization
                        HelmRelease
                        HelmChart
                        HelmRepository
                        ImageRepository
                        ImagePolicy
                        ImageUpdateAutomation
                        OCIRepository
                        Terraform
...
```

```
kubectl -n flux-system describe crd receivers.notification.toolkit.fluxcd.io
...
                    Kind:
                      Description:  Kind of the referent
                      Enum:
                        Bucket
                        GitRepository
                        Kustomization
                        HelmRelease
                        HelmChart
                        HelmRepository
                        ImageRepository
                        ImagePolicy
                        ImageUpdateAutomation
                        OCIRepository
                        Terraform
                      Type:  string
...
```

```
kubectl -n flux-system describe clusterrole crd-controller-flux-system
Name:                               crd-controller-flux-system
Labels:                             app.kubernetes.io/instance=flux-system
                                    app.kubernetes.io/part-of=flux
                                    app.kubernetes.io/version=v0.34.0
                                    kustomize.toolkit.fluxcd.io/name=flux-system
                                    kustomize.toolkit.fluxcd.io/namespace=flux-system
Annotations:                        PolicyRule:
  Resources                         Non-Resource URLs  Resource Names  Verbs
  ---------                         -----------------  --------------  -----
...
  *.infra.contrib.fluxcd.io         []                 []              [*]
...
```

My Alert specification is the following
```
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: slack
  namespace: flux-system
spec:
  type: slack
  channel: general
  secretRef:
    name: slack-url
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: flux-cd
  namespace: flux-system
spec:
  summary: "Flux CD"
  providerRef:
    name: slack
  eventSeverity: error
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
    - kind: Terraform
      name: '*'

```

It works fine for `GitRepositiory` resources, but for `Terraform` resource I get no notification at all, and I don't see anything in the notification-controller logs, not even a mention whether a rule was not satisfied

Is there anything else I'm missing on the setup?

**Comment by chanwit** [comment]
It seems to be the correct configuration to me. I did try the similar setup and it worked.
Maybe you would try specifying apiVersion for your event source?

```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: terraform-slack
  namespace: default
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - apiVersion: infra.contrib.fluxcd.io/v1alpha1
      kind: Terraform
      name: '*'
```
