### ISSUE TITLE
support mattermost Provider type

### ISSUE THREAD

**Issue by resham7** [fluxcd/notification-controller#522]
hey,
I want to use Mattermost to send notifications from flux to Mattermost, created secrets for Mattermost's incoming hook here are yaml files 

```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: mattermost
  namespace: flux-system
spec:
  type: mattermost
  channel: general
  secretRef:
    name: mattermost-url
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: default-notifications
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: HelmRepository
      name: '*'
    - kind: Kustomization
      name: '*'
```

getting this error

```
alert.notification.toolkit.fluxcd.io/default-notifications created
The Provider "mattermost" is invalid: spec.type: Unsupported value: "mattermost": supported values: "slack", "discord", "msteams", "rocket", "generic", "generic-hmac", "github", "gitlab", "bitbucket", "azuredevops", "googlechat", "webex", "sentry", "azureeventhub", "telegram", "lark", "matrix", "opsgenie", "alertmanager", "grafana", "githubdispatch"```

**Comment by makkes** [comment]
For reference you'll find the list of supported providers [here](https://fluxcd.io/flux/components/notification/provider/#type).

**Comment by resham7** [comment]
so I can not use Mattermost anyhow?

**Comment by stefanprodan** [comment]
Mattermost should be compatible with Slack, so set the `type: slack`

**Comment by resham7** [comment]
it is created but I'm not receiving any notification in my channel

**Comment by stefanprodan** [comment]
```
  providerRef:
    name: slack
 ```

This is wrong, it should be mattermost

**Comment by resham7** [comment]
how i can do that can you please help

**Comment by stefanprodan** [comment]
```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: mattermost
  namespace: flux-system
spec:
  type: slack
  channel: general
  secretRef:
    name: mattermost-url
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: default-notifications
  namespace: flux-system
spec:
  providerRef:
    name: mattermost
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: HelmRepository
      name: '*'
    - kind: Kustomization
      name: '*'
 ```

Use the above, then look in the notification-controller logs with `kubectl logs <nc-pod>`
