### ISSUE TITLE
Alert: "error":"postMessage failed: failed to execute request: context  deadline exceeded"

### ISSUE THREAD

**Issue by saimissioncloud** [fluxcd/notification-controller#740]
Hi Team,

I'm trying to trigger application testing pipeline after helmrelease succeeded using `generic webhook` and I'm getting below error.
I'm using notification controller version` fluxcd/notification-controller:v1.1.0`

```
{"level":"error","ts":"2024-02-15T04:32:29.110Z","logger":"event-server","msg":"failed to send notification","eventInvolvedObject":{"kind":"HelmRelease","namespace":"default","name":"releasename","uid":"ae67a2f7
-8037-416c-a14f-3293a4673eb9","apiVersion":"helm.toolkit.fluxcd.io/v2beta1","resourceVersion":"559098322"},"alert":{"name":"fluxalert","namespace":"default"},"error":"postMessage failed: failed to execute request: context 
deadline exceeded","stacktrace":"github.com/fluxcd/notification-controller/internal/server.(*EventServer).handleEvent.func1.1\n\tgithub.com/fluxcd/notification-controller/internal/server/event_handlers.go:260"} 
```

Here is my configuration

**secret.yaml**
```
apiVersion: v1
kind: Secret
metadata:
  name: token
  namespace: default
stringData:
  headers: |
    X-API-EMAIL: emailid
    X-API-TOKEN: token
```

**provider.yaml**
```
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: fluxprovider
spec:
  type: generic
  address: https://pipelineurl/trigger
  secretRef:
    name: token
```

**alert.yaml**
```
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: fluxalert
spec:
  providerRef:
    name: fluxprovider
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      name: releasename
  inclusionList:
    - ".*succeeded.*"
```
