### ISSUE TITLE
Pod support for alerts

### ISSUE THREAD

**Issue by pulkitanz** [fluxcd/notification-controller#792]
I was wondering if there is something planned to add Pod in Slack alerts, this will help us a lot in configuring alerts for breaking `kustomize controller`.

```
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: grafana
  namespace: monitoring
spec:
  providerRef:
    name: grafana
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
      namespace: flux-system
  - kind: Pod
      name: '*'
      namespace: flux-system
    
```

Is there any other way to configure pod alerts using notification-controller?
